CRITICAL - 2022-04-18 04:50:18 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\Exceptions::extend() in /home/u7653345/public_html/matt.shennx.net/bapsi2/app/Views/errors/html/error_404.php:1
Stack trace:
#0 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(234): include()
#1 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#2 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Exceptions\PageNotFoundException), 404)
#3 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#4 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-04-18 04:50:34 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\Exceptions::extend() in /home/u7653345/public_html/matt.shennx.net/bapsi2/app/Views/errors/html/error_404.php:1
Stack trace:
#0 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(234): include()
#1 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#2 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Exceptions\PageNotFoundException), 404)
#3 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#4 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-04-18 04:50:35 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\Exceptions::extend() in /home/u7653345/public_html/matt.shennx.net/bapsi2/app/Views/errors/html/error_404.php:1
Stack trace:
#0 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(234): include()
#1 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#2 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Exceptions\PageNotFoundException), 404)
#3 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#4 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-04-18 04:50:35 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\Exceptions::extend() in /home/u7653345/public_html/matt.shennx.net/bapsi2/app/Views/errors/html/error_404.php:1
Stack trace:
#0 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(234): include()
#1 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#2 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Exceptions\PageNotFoundException), 404)
#3 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#4 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-04-18 04:50:46 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\Exceptions::extend() in /home/u7653345/public_html/matt.shennx.net/bapsi2/app/Views/errors/html/error_404.php:1
Stack trace:
#0 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(234): include()
#1 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#2 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Exceptions\PageNotFoundException), 404)
#3 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#4 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-04-18 04:50:57 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\Exceptions::extend() in /home/u7653345/public_html/matt.shennx.net/bapsi2/app/Views/errors/html/error_404.php:1
Stack trace:
#0 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(234): include()
#1 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#2 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Exceptions\PageNotFoundException), 404)
#3 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#4 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-04-18 04:51:14 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\Exceptions::extend() in /home/u7653345/public_html/matt.shennx.net/bapsi2/app/Views/errors/html/error_404.php:1
Stack trace:
#0 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(234): include()
#1 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#2 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Exceptions\PageNotFoundException), 404)
#3 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#4 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-04-18 04:51:23 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\Exceptions::extend() in /home/u7653345/public_html/matt.shennx.net/bapsi2/app/Views/errors/html/error_404.php:1
Stack trace:
#0 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(234): include()
#1 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#2 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Exceptions\PageNotFoundException), 404)
#3 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#4 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-04-18 04:51:34 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\Exceptions::extend() in /home/u7653345/public_html/matt.shennx.net/bapsi2/app/Views/errors/html/error_404.php:85
Stack trace:
#0 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(234): include()
#1 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#2 /home/u7653345/public_html/matt.shennx.net/bapsi2/system/Debug/Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Exceptions\PageNotFoundException), 404)
#3 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#4 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
